version: '3.1'

services:

  db:
    container_name: db
    image: alejovicu/simple-web-db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: simple-web
    ports:
      - "3306:3306"

  app:
    container_name: app
    image: alejovicu/simple-web-app
    ports:
      - "8080:80"

  # workbench:
  #   image: linuxserver/mysql-workbench
  #   container_name: workbench
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - /tmp/workbench:/config
  #     - ./db:/home
  #   ports:
  #     - 3000:3000
  #   cap_add:
  #     - IPC_LOCK
  #   restart: unless-stopped